### ISSUE TITLE
__len__ of the Pytorch dataset

### ISSUE THREAD

**Issue by paulagd** [sh0416/bpr#1]
Hi,

In the function __len__ of the pytorch dataset you return `10*len(self.pair)`. Could you explain why? 

If I debug the code, **len(self.pair)** would be equals to **802,406**, which I understand as the number of links of the training set (as the total number of links for ml-1M is 1M). However, if you multiply it by a factor 10, you get a dataset of len **8,024,060**, which I don't understand.

Thank you in advance!

**Comment by sh0416** [comment]
First, the index of dataset is meaningless.
In the first line of ‘__iter__’ in dataset, I redefine idx value.
I sample user idx as many as batch size and compose triplet based on possible pair.
So, The number of iteration per one epoch is 10*self.pair.
If you want to change the number of iteration, then change that value.
Hope it will help. :)

**Comment by paulagd** [comment]
Yes! Thank you very much :)
